// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1b4a0Kmnt5DFC-lrJiI42VD1wEo0JZFQ',
    appId: '1:285085371704:web:e3f4cc482f2b933f04c5cd',
    messagingSenderId: '285085371704',
    projectId: 'snapbook-mp',
    authDomain: 'snapbook-mp.firebaseapp.com',
    storageBucket: 'snapbook-mp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwr3YHzZgEDltft2oeifukwnzKkUj627I',
    appId: '1:285085371704:android:c4a3852b342f043404c5cd',
    messagingSenderId: '285085371704',
    projectId: 'snapbook-mp',
    storageBucket: 'snapbook-mp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQVqeIPJsfDX_Cc84Y6YSp2aQO_8I783Y',
    appId: '1:285085371704:ios:aecbf2359d0dcf0504c5cd',
    messagingSenderId: '285085371704',
    projectId: 'snapbook-mp',
    storageBucket: 'snapbook-mp.firebasestorage.app',
    iosBundleId: 'com.example.snapbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQVqeIPJsfDX_Cc84Y6YSp2aQO_8I783Y',
    appId: '1:285085371704:ios:aecbf2359d0dcf0504c5cd',
    messagingSenderId: '285085371704',
    projectId: 'snapbook-mp',
    storageBucket: 'snapbook-mp.firebasestorage.app',
    iosBundleId: 'com.example.snapbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1b4a0Kmnt5DFC-lrJiI42VD1wEo0JZFQ',
    appId: '1:285085371704:web:a2e2087de8256f3e04c5cd',
    messagingSenderId: '285085371704',
    projectId: 'snapbook-mp',
    authDomain: 'snapbook-mp.firebaseapp.com',
    storageBucket: 'snapbook-mp.firebasestorage.app',
  );
}
